### ISSUE TITLE
Missing Docs for keys in Realm Description Sample

### ISSUE THREAD

**Issue by staypufd** [jgrodziski/keycloak-clojure#15]
### Missing Docs for keys in Realm Description Sample

The following keys don’t have docs in the Realm Description Sample example.

1. :username-creator-fn
1. :generated-users-by-group-and-role

**Comment by jgrodziski** [comment]
Ok done with an example: [Declarative Setup](https://github.com/jgrodziski/keycloak-clojure#declarative-setup)
