### ISSUE TITLE
Debug Level Logs in 1.16.5

### ISSUE THREAD

**Issue by Wegi** [jgrodziski/keycloak-clojure#22]
Hi,

it seems that debug level prints are enabled in 1.16.5 across the board. Just letting you know. :)

Kind Regards

Alex

**Comment by jgrodziski** [comment]
Hi Alexander,

Maybe that's because I removed the `logback.xml` file that should have never been there in the Jar in the first place. 
If you add a `Keycloak.*` logger with WARN level, does it work as previously?

**Comment by Wegi** [comment]
Adding a logback.xml to my path solved it. Maybe it would help others in the future adding this information to the README somewhere. :)
