### ISSUE TITLE
Send-Verification-Mail: Route existent?

### ISSUE THREAD

**Issue by n2o** [jgrodziski/keycloak-clojure#38]
Hello,

short question, can't find it in the docs. Is there a function to send a verification mail? This is the route: https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_sendverifyemail

Could be very useful, since, as far as I know, one can only send verification mails with an explicit redirect uri via the API. I don't like this, because now I need to do the request on my own, but seems to be the only option. (I want to redirect the user to a "success"-page when she registered and verified her mail).

Thanks!

**Comment by jgrodziski** [comment]
Added starting from version `1.25.0`
see: [send-veriication-email](https://cljdoc.org/d/keycloak-clojure/keycloak-clojure/1.25.1/api/keycloak.user#send-verification-email) and [execute-actions-email](https://cljdoc.org/d/keycloak-clojure/keycloak-clojure/1.25.1/api/keycloak.user#execute-actions-email)
