### ISSUE TITLE
Refactor the keycloak.deployment/extract to include all the properties from JsonWebToken and IDToken

### ISSUE THREAD

**Issue by safehammad** [jgrodziski/keycloak-clojure#46]
Many thanks for creating this library! I'm enjoying learning it.

In my web application I have user entered data which I'd like to link back to the relevant user in Keycloak and my first instinct would be to use the Keycloak User ID / Subject as the reference. The middleware functions in `keycloak-clojure` verify a user's access token and extract values from it to return to the web application, but the extracted values don't include the User ID.

Is this intentional because I shouldn't be referencing the User ID in my application? In which case, is it best practice to reference the Username instead? Or should I be querying Keycloak again for the User ID?

Otherwise, is there scope to add an `:id` field (or `:user-id` or `:subject`?) to the extracted data in the `extract` function in `keycloak.deployment`, for example:

```clojure
(defn extract
  ...
  ^keycloak.deployment.ClojureAccessToken [^org.keycloak.representations.AccessToken access-token]
  (map->ClojureAccessToken {:username              (.getPreferredUsername access-token)
                            :id                    (.getSubject access-token)  ; <- new value
...
```
Many thanks for your help!

**Comment by jgrodziski** [comment]
Hi Safe,

Thanks for your kind words.
Yes indeed I can refactor the `extract` function to include the properties from [JsonWebToken](https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/core/src/main/java/org/keycloak/representations/JsonWebToken.java) and [IDToken](https://github.com/keycloak/keycloak/blob/bfce612641a70e106b20b136431f0e4046b5c37f/core/src/main/java/org/keycloak/representations/IDToken.java).
It's refactored in version `1.28.4` can you test it?

**Comment by jgrodziski** [comment]
You can also to the other way and include some application data as attributes of the user when you create it, you can then include the attribute key/value with a mapper (in a declarative or imperative way) to have them in the token. It works very well given the value are not too large, and it avoids reissuing requests to get that data.
E.g. of group and attribute mappers declaration with starter function:
```
(def mappers [{:name   "group-mapper"
               :type   "oidc-group-membership-mapper"
               :config {"claim.name" "group"}}
              {:name   "org-id-mapper"
               :type   "oidc-usermodel-attribute-mapper"
               :config {"multivalued"          "false"
                        "user.attribute"       "org-id"
                        "claim.name"           "org-id"
                        "jsonType.label"       "String"}}
              {:name   "managed-accounts-mapper"
               :type   "oidc-usermodel-attribute-mapper"
               :config {"multivalued"          "true"
                        "user.attribute"       "managed-accounts"
                        "claim.name"           "managed-accounts"
                        "jsonType.label"       "String"}}])
```

or you can use the imperative side-effect function:
```
(create-protocol-mapper! admin-client "myrealm" "myclient-id"
                           (user-attribute-mapper "testuam" "org-id" "org-id" "String"))
```

**Comment by safehammad** [comment]
Thank you so much for the very quick turnaround! I've updated to `1.28.4` and tested it and it works perfectly. And adding custom user attributes with a mapper to put them in the token looks very useful. I'll be sure to have a look at that.

Thank you once again!
