### ISSUE TITLE
`search-users` has hardcoded min/max search boundaries

### ISSUE THREAD

**Issue by neuromantik33** [jgrodziski/keycloak-clojure#51]
The function `keycloak.user/search-user` has a hardcoded first and max results to 0 and 10. It's a little problematic in our use case where a prexisting login is simply a 2 character login and is present in too many login strings.
Unfortunately limiting the search won't help since we are importing roles from our old oauth provider and the `keycloak.user/get-user-realm-roles` doesn't provide an api to refine the search.
Of course there is a workaround but it involves duplicating a lot of code in the ku namespace and it won't be nice to be able to parameterize the search results using bindings (an optional `& opts` map won't work since it will break the existing `user-id` API which has a simple and long form.

Any suggestions are welcome.

**Comment by neuromantik33** [comment]
My current workaround is to use `(with-redefs [keycloak.user/search-user nolimit-search-user] ...)` maybe that's sufficient but we are using it everywhere.

**Comment by jgrodziski** [comment]
Hi Nicolas,
Yes the search-user function has not been very well thought out....
I've released a new version `1.30.0` with more arities to the `search-user` function that add the first and max results arguments (not changing the existing ones for compatibility reasons). 
I've also add a `search-user-by-attributes` function close to the KC API one.

**Comment by neuromantik33** [comment]
Ok it seems a bit extreme in my opinion to have so many arities but I understand that you don't want to break any existing APIs. An keyword options map like
```clojure
(defn search-users
  [keycloak-client realm-name username & {:keys[first-name last-name email from to]}]
  ...
```
would have been the most idiomatic but thanks anyways ;)

**Comment by jgrodziski** [comment]
Yes, I agree, the user namespace is dirty and was implemented in a hurry and I didn't take time to refactor it and also don't want to break the compatibility 😞
