### ISSUE TITLE
Key rotation

### ISSUE THREAD

**Issue by bpalermo** [jgrodziski/keycloak-clojure#9]
Hi,

Does it supports key rotation?

Looking at 'keycloak.clj' file on the sample directory, it appears to have a static key ID.

Thanks,
Bruno

**Comment by jgrodziski** [comment]
There is no key rotation. But you can implement it quite easily by generating a new client on the Keycloak server and retrieve it on your client.
The point is to use static key only in "secure" environment, the most secure way in "unsecure" env (called "public" in oidc vocabulary) is to use very short lived token (AccessToken) like any web application and change your credentials frequently.

**Comment by bpalermo** [comment]
In that case I will have to change the key ID on the source code correctly?

**Comment by jgrodziski** [comment]
I don't understand what you means by "Key ID".
Every piece of software interacting with a Keycloak server is called a `client` and you reference it through a clientId, that client has either a `client-secret` or an `identifier/password` tuple. The `client-secret` for a client can be retrieved if you have an `admin` keycloak client (the object of the adapter lib, not the concept) thanks to the `keycloak.deployment/deployment-for-realms` function.

**Comment by bpalermo** [comment]
Every token issued by the Keycloak server is signed with a key. This key ID is present on the token header, for example:

`{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "ObqWcjqrcLcwZ2I8rOwqr5Tz9uVrG8zLFyJNAvdqp6w"
}`

When a server wants to authenticate the token presented by the user, it requests that key from the Keycloak server with the corresponding ID.

After that the server can check the token signature and see if it matches.

The flow is defined by OpenID.

**Comment by jgrodziski** [comment]
Ok I better understand what you mean now.
The key id is actually extracted from the token during every token verification. See the source of the [`keycloak.deployment/verify`](https://github.com/jgrodziski/keycloak-clojure/blob/master/src/keycloak/deployment.clj#L84) function.
